"""add ethereum columns

Revision ID: bad255cd9b54
Revises: c0b836c29c43
Create Date: 2026-05-07 10:21:16.185024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad255cd9b54'
down_revision: Union[str, Sequence[str], None] = 'c0b836c29c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger', sa.Column('eth_tx_hash', sa.String(length=66), nullable=True))
    op.add_column('ledger', sa.Column('eth_chain_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger', 'eth_chain_id')
    op.drop_column('ledger', 'eth_tx_hash')
    # ### end Alembic commands ###
